config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: "omniauth_callbacks",
    session: "sessions",
    registrations: "registrations"
  }

  devise_scope :user do
    delete "/sign_out" => "devise/sessions#destroy"
    get "/enter" => "registrations#new", as: :new_user_registration_path
  end

  namespace :admin do
    DashboardManifest::DASHBOARDS.each do |dashboard_resource|
      resources dashboard_resource
    end

    root controller: DashboardManifest::ROOT_DASHBOARD, action: :index
  end

  namespace :internal do
    resources :comments
    resources :articles
    resources :tags
    resources :welcome, only: %i[index create]
    resources :broadcasts
    resources :users do
      member do
        post "banish"
      end
    end
    resources :events
    resources :dogfood, only: [:index]
    resources :buffer_updates, only: [:create]
    resources :articles, only: %i[index update] do
      get "rss_articles", on: :collection
    end
    resources :members, only: [:index]
    resources :events
    resources :feedback_messages, only: %i[update show]
    resources :reports, only: %i[index update show], controller: "feedback_messages" do
      collection do
        post "send_email"
        post "create_note"
        post "save_status"
      end
    end
    mount Flipflop::Engine => "/features"
  end

  namespace :api, defaults: { format: "json" } do
    scope module: :v0,
          constraints: ApiConstraints.new(version: 0, default: true) do
      resources :articles, only: %i[index show create update] do
        collection do
          get "/onboarding", to: "articles#onboarding"
        end
      end
      resources :comments
      resources :podcast_episodes
      resources :reactions, only: [:create] do
        collection do
          post "/onboarding", to: "reactions#onboarding"
        end
      end
      resources :users, only: %i[index show] do
        collection do
          get "/sidebar_suggestions", to: "users#sidebar_suggestions"
        end
      end
      resources :tags, only: [:index] do
        collection do
          get "/onboarding", to: "tags#onboarding"
        end
      end
      resources :follows, only: [:create]
      resources :github_repos, only: [:index] do
        collection do
          post "/update_or_create", to: "github_repos#update_or_create"
        end
      end
    end
  end

  namespace :notifications do
    resources :counts, only: [:index]
    resources :reads, only: [:create]
  end

  resources :messages, only: [:create]
  resources :chat_channels, only: %i[index show create update]
  resources :chat_channel_memberships, only: %i[create update destroy]
  resources :articles, only: %i[update create destroy]
  resources :comments, only: %i[create update destroy]
  resources :users, only: [:update]
  resources :reactions, only: %i[index create]
  resources :feedback_messages, only: %i[index create]
  get "/reports/:slug", to: "feedback_messages#show"
  resources :organizations, only: %i[update create]
  resources :followed_articles, only: [:index]
  resources :follows, only: %i[show create]
  resources :giveaways, only: %i[create update]
  resources :image_uploads, only: [:create]
  resources :blocks
  resources :notifications, only: [:index]
  resources :tags, only: [:index]
  resources :analytics, only: [:index]
  resources :stripe_subscriptions, only: %i[create update destroy]
  resources :stripe_active_cards, only: %i[create update destroy]
  resources :live_articles, only: [:index]
  resources :github_repos, only: %i[create update]
  resources :buffered_articles, only: [:index]
  resources :events, only: %i[index show]
  resources :additional_content_boxes, only: [:index]
  resources :videos, only: %i[create new]
  resources :video_states, only: [:create]
  resources :twilio_tokens, only: [:show]
  resources :html_variants
  resources :html_variant_trials, only: [:create]
  resources :html_variant_successes, only: [:create]
  resources :push_notification_subscriptions, only: [:create]

  get "/notifications/:username" => "notifications#index"
  patch "/onboarding_update" => "users#onboarding_update"
  get "email_subscriptions/unsubscribe"
  post "/chat_channels/:id/moderate" => "chat_channels#moderate"
  post "/chat_channels/:id/open" => "chat_channels#open"
  get "/connect" => "chat_channels#index"
  get "/connect/:slug" => "chat_channels#index"

  post "/pusher/auth" => "pusher#auth"

  get "/social_previews/article/:id" => "social_previews#article"
  get "/social_previews/user/:id" => "social_previews#user"
  get "/social_previews/organization/:id" => "social_previews#organization"
  get "/social_previews/tag/:id" => "social_previews#tag"

  post "membership-action" => "stripe_subscriptions#create"

  get "/async_info/base_data", controller: "async_info#base_data", defaults: { format: :json }

  get "/hello-goodbye-to-the-go-go-go",
      to: redirect("ben/hello-goodbye-to-the-go-go-go")
  get "/dhh-on-the-future-of-rails",
      to: redirect("ben/dhh-on-the-future-of-rails")
  get "/christopher-chedeau-on-the-philosophies-of-react",
      to: redirect("ben/christopher-chedeau-on-the-philosophies-of-react")
  get "/javascript-fatigue-buzzword",
      to: redirect("ben/javascript-fatigue-buzzword")
  get "/chris-seaton-making-ruby-fast",
      to: redirect("ben/chris-seaton-making-ruby-fast")
  get "/communicating-intent-the-perpetually-misunderstood-ruby-bang",
      to: redirect("tom/communicating-intent-the-perpetually-misunderstood-ruby-bang")
  get "/quick-tip-grepping-rails-routes",
      to: redirect("tom/quick-tip-grepping-rails-routes")
  get "/use-cases-for-githubs-new-direct-upload-feature",
      to: redirect("ben/use-cases-for-githubs-new-direct-upload-feature")
  get "/this-blog-post-was-written-using-draft-js",
      to: redirect("ben/this-blog-post-was-written-using-draft-js")
  get "/the-future-of-software-development",
      to: redirect("ben/the-future-of-software-development")
  get "/the-zen-of-missing-out-on-the-next-great-programming-tool",
      to: redirect("ben/the-zen-of-missing-out-on-the-next-great-programming-tool")
  get "/the-joy-and-benefit-of-being-an-early-adopter-in-programming",
      to: redirect("ben/the-joy-and-benefit-of-being-an-early-adopter-in-programming")
  get "/watkinsmatthewp/every-developer-should-write-a-personal-automation-api",
      to: redirect("anotherdevblog/every-developer-should-write-a-personal-automation-api")

  post "users/join_org" => "users#join_org"
  post "users/leave_org" => "users#leave_org"
  post "users/add_org_admin" => "users#add_org_admin"
  post "users/remove_org_admin" => "users#remove_org_admin"
  post "users/remove_from_org" => "users#remove_from_org"
  delete "users/remove_association", to: "users#remove_association"
  delete "users/destroy", to: "users#destroy"
  post "organizations/generate_new_secret" => "organizations#generate_new_secret"

  get "/about" => "pages#about"
  get "/privacy" => "pages#privacy"
  get "/terms" => "pages#terms"
  get "/contact" => "pages#contact"
  get "/merch" => "pages#merch"
  get "/rlygenerator" => "pages#generator"
  get "/orlygenerator" => "pages#generator"
  get "/rlyslack" => "pages#generator"
  get "/rlyweb" => "pages#rlyweb"
  get "/rly" => "pages#rlyweb"
  get "/code-of-conduct" => "pages#code_of_conduct"
  get "/report-abuse" => "pages#report_abuse"
  get "/infiniteloop" => "pages#infinite_loop"
  get "/faq" => "pages#faq"
  get "/live" => "pages#live"
  get "/swagnets" => "pages#swagnets"
  get "/welcome" => "pages#welcome"
  get "/💸", to: redirect("t/hiring")
  get "/security", to: "pages#bounty"
  get "/survey", to: redirect("https://dev.to/ben/final-thoughts-on-the-state-of-the-web-survey-44nn")
  get "/now" => "pages#now"
  get "/membership" => "pages#membership"
  get "/events" => "events#index"
  get "/workshops", to: redirect("events")
  get "/sponsorship-info" => "pages#sponsorship_faq"
  get "/sponsors" => "pages#sponsors"
  get "/search" => "stories#search"
  post "articles/preview" => "articles#preview"
  post "comments/preview" => "comments#preview"
  get "/freestickers" => "giveaways#new"
  get "/freestickers/edit" => "giveaways#edit"
  get "/scholarship", to: redirect("/p/scholarships")
  get "/scholarships", to: redirect("/p/scholarships")
  get "/memberships", to: redirect("/membership")
  get "/shop", to: redirect("https://shop.dev.to/")

  post "/fallback_activity_recorder" => "ga_events#create"

  scope "p" do
    pages_actions = %w[rly rlyweb welcome twitter_moniter editor_guide information
                       markdown_basics scholarships wall_of_patrons membership_form badges]
    pages_actions.each do |action|
      get action, action: action, controller: "pages"
    end
  end

  get "/settings/(:tab)" => "users#edit"
  get "/signout_confirm" => "users#signout_confirm"
  get "/dashboard" => "dashboards#show"
  get "/dashboard/:which" => "dashboards#show",
      constraints: {
        which: /organization|user_followers|following_users|reading/
      }
  get "/dashboard/:username" => "dashboards#show"

  unless Rails.env.production?
    get "/rails/mailers" => "rails/mailers#index"
    get "/rails/mailers/*path" => "rails/mailers#preview"
  end

  get "/new" => "articles#new"
  get "/new/:template" => "articles#new"

  get "/pod" => "podcast_episodes#index"
  get "/readinglist" => "reading_list_items#index"

  get "/feed" => "articles#feed", as: "feed", defaults: { format: "rss" }
  get "/feed/:username" => "articles#feed",
      as: "user_feed", defaults: { format: "rss" }
  get "/rss" => "articles#feed", defaults: { format: "rss" }

  get "/tag/:tag" => "stories#index"
  get "/t/:tag" => "stories#index"
  get "/t/:tag/edit", to: "tags#edit"
  patch "/tag/:id", to: "tags#update"
  get "/t/:tag/top/:timeframe" => "stories#index"
  get "/t/:tag/:timeframe" => "stories#index",
      constraints: { timeframe: /latest/ }

  get "/badge/:slug" => "badges#show"

app/controllers/admin/users_controller.rb
module Admin
  class UsersController < Admin::ApplicationController
    def update
      user = User.find(params[:id])
      UserRoleService.new(user, current_user.id).check_for_roles(params[:user])
      if user.errors.messages.blank? && user.update(user_params)
        flash[:notice] = "User successfully updated"
        redirect_to "/admin/users/#{params[:id]}"
      else
        render :new, locals: { page: Administrate::Page::Form.new(dashboard, user) }
      end
    end

    private

    def user_params
      accessible = %i[name
                      email
                      username
                      twitter_username
                      github_username
                      profile_image
                      website_url
                      summary
                      email_newsletter
                      email_comment_notifications
                      email_follower_notifications
                      organization_id
                      org_admin
                      bg_color_hex
                      text_color_hex
                      employer_name
                      employer_url
                      employment_title
                      currently_learning
                      available_for
                      mostly_work_with
                      currently_hacking_on
                      location
                      email_public
                      education
                      looking_for_work
                      looking_for_work_publicly
                      contact_consent
                      feed_url
                      feed_mark_canonical
                      feed_admin_publish_permission
                      reputation_modifier
                      onboarding_package_requested
                      onboarding_package_fulfilled
                      onboarding_package_requested_again
                      shipping_name
                      shipping_company
                      shipping_address
                      shipping_address_line_2
                      shipping_city
                      shipping_state
                      shipping_country
                      shipping_postal_code
                      shirt_size
                      shirt_gender
                      saw_onboarding
                      scholar_email]
      accessible << %i[password password_confirmation] unless params[:user][:password].blank?
      params.require(:user).permit(accessible)
    end
  end
end

app/controllers/api/v0/users_controller.rb
module Api
  module V0
    class UsersController < ApplicationController
      def index
        if !user_signed_in? || less_than_one_day_old?(current_user)
          usernames = ["ben", "jess", "peter", "maestromac", "andy", "liana"]
          @users = User.where(username: usernames)
          return
        end
        if params[:state] == "follow_suggestions"
          @users = Suggester::Users::Recent.new(current_user).suggest
        elsif params[:state] == "sidebar_suggestions"
          given_tag = params[:tag]
          @users = Suggester::Users::Sidebar.new(current_user, given_tag).suggest.sample(3)
        end
      end

      def show
        @user = if params[:id] == "by_username"
                  User.find_by_username(params[:url])
                else
                  User.find(params[:id])
                end
      end

      def less_than_one_day_old?(user)
        range = 1.day.ago.beginning_of_day..Time.current
        user_identity_age = user.github_created_at ||
          user.twitter_created_at || 8.days.ago
        # last one is a fallback in case both are nil
        range.cover? user_identity_age
      end
    end
  end
end

app/controllers/internal/application_controller.rb
class Internal::ApplicationController < ApplicationController
  before_action :authorize_admin

  private

  def authorize_admin
    authorize :admin, :show?
  end
end

app/controllers/internal/articles_controller.rb
class Internal::ArticlesController < Internal::ApplicationController
  layout "internal"

  def index
    case params[:state]

    when /not\-buffered/
      days_ago = params[:state].split("-")[2].to_f
      @articles = Article.
        where(last_buffered: nil).
        includes(:user).
        includes(:buffer_updates).
        order("positive_reactions_count DESC").
        page(params[:page]).
        where("published_at > ? OR crossposted_at > ?", days_ago.days.ago, days_ago.days.ago).
        limited_columns_internal_select.
        per(50)
    when /top\-/
      @articles = Article.
        where("published_at > ?", params[:state].split("-")[1].to_i.months.ago).
        includes(:user).
        includes(:buffer_updates).
        order("positive_reactions_count DESC").
        page(params[:page]).
        limited_columns_internal_select.
        per(50)
    when "boosted-additional-articles"
      @articles = Article.
        includes(:user).
        order("published_at DESC").
        includes(:buffer_updates).
        boosted_via_additional_articles.
        page(params[:page]).
        per(100).
        limited_columns_internal_select
    when "chronological"
      @articles = Article.
        where(published: true).
        order("published_at DESC").
        page(params[:page]).
        limited_columns_internal_select.
        per(50)
    else # MIX
      @articles = Article.
        where(published: true).
        order("hotness_score DESC").
        page(params[:page]).
        limited_columns_internal_select.
        per(50)

      @featured_articles = Article.
        where(published: true).
        or(Article.where(published_from_feed: true)).
        where(featured: true).
        where("featured_number > ?", Time.current.to_i).
        includes(:user).
        includes(:buffer_updates).
        limited_columns_internal_select.
        order("featured_number DESC")
    end
  end

  def show
    @article = Article.find(params[:id])
  end

  def update
    article = Article.find(params[:id])
    article.featured = article_params[:featured].to_s == "true"
    article.approved = article_params[:approved].to_s == "true"
    article.live_now = article_params[:live_now].to_s == "true"
    article.email_digest_eligible = article_params[:email_digest_eligible].to_s == "true"
    article.boosted_additional_articles = article_params[:boosted_additional_articles].to_s == "true"
    article.boosted_dev_digest_email = article_params[:boosted_dev_digest_email].to_s == "true"
    article.update!(article_params)
    if article.live_now
      Article.where.not(id: article.id).where(live_now: true).update_all(live_now: false)
    end
    CacheBuster.new.bust "/live_articles"
    # raise
    render body: nil
    # redirect_to "/internal/articles"
  end

  private

  def article_params
    params.require(:article).permit(:featured,
                                    :social_image,
                                    :body_markdown,
                                    :approved,
                                    :live_now,
                                    :email_digest_eligible,
                                    :boosted_additional_articles,
                                    :boosted_dev_digest_email,
                                    :main_image_background_hex_color,
                                    :featured_number)
  end
end

app/views/internal/users/edit.html.erb
<h1><a href="<%= @user.path %>"><%= @user.name %></a></h1>
<h2>@<%= @user.username %></h2>
<h4><%= @user.comments.size %> comments</h4>
<h4><%= @user.articles.size %> articles</h4>
<h4><%= @user.reactions.size %> reactions</h4>
<h4>Joined <%= @user.created_at.to_formatted_s(:long_ordinal) %></h4>
<% if @user.banned %>
  <h1 style="color:red">User is banned</h1>
  <% @user.notes.each do |note| %>
    <b><%= note.reason %></b> | <%= note.content %>
  <% end %>
<% else %>
  <div class="row">
    <% if @user.comments.where("created_at < ?", 7.days.ago).empty? %>
      <%= form_for(@user, :url => banish_internal_user_path(@user), :html => {:method => :post, :onsubmit => "confirm('Are you sure? This is extremely destructive and will change their username to @spam_###. Do not do it lightly.')"}) do %>
        <button class="btn btn-danger" style="font-size:2em;">Banish User for Spam!</button>
      <% end %>
      <em>This is extremely destructive and will change their username to @spam_###. Do not do it lightly.</em>
    <% else %>
      <em>You cannot take admin action from this view because this is not a newish user. For safety.</em>
    <% end %>
  </div>
<% end %>

app/views/internal/users/index.html.erb
<h3 class="top-nav">
  <a href="/internal/users">All Users</a> ||
  <a href="/internal/users?state=mentors">Mentors Only </a>||
  <a href="/internal/users?state=mentees">Mentees Only</a>
</h3>
<% if params[:state] == "mentors" %>
  <h1>Mentors</h1>
<% elsif params[:state] == "mentees" %>
  <h1>Mentees</h1>
<% else %>
  <h1>All Users</h1>
<% end %>
<%= paginate @users %>
<% @users.each do |user| %>
  <div class="row">
    <h2><%= user.name%></h2>
    <h3><a href="/internal/users/<%= user.id %>" target="_blank">@<%= user.username%></a></h3>
  </div>
<% end %>
<%= paginate @users %>

app/views/internal/users/show.html.erb
<div class="row">
  <h1>
    <%= @user.name%><a href="/<%= @user.username %>" target="_blank"> (@<%= @user.username %>)</a>
  </h1>
  <p><em>Member since <%= @user.created_at.strftime("%d %B %Y %H:%M UTC") %></em></p>
  <% if @user.banned %>
    <p style="background-color:red;color:white">BANNED USER</p>
    <p>Reason for banning: <%= @user.reason_for_ban %></p>
  <% elsif @user.warned %>
    <p style="background-color:orange;color:white">User Status: Warned</p>
    <p>Reason for warning: <%= @user.reason_for_warning %></p>
  <% else %>
    <p style="color:green">Member in good standing</p>
  <% end %>
  <hr/>
  <h3><u>Basic Info</u></h3>
  <p><strong>Email:</strong> <%= @user.email %></p>
  <% if @user.feed_admin_publish_permission %>
    <p><strong>Admins can publish from RSS ✅</strong></p>
  <% else %>
    <p>Admins cannot publish from RSS ❌<p>
  <% end %>
  <h3><u>Badges</u></h3>
  <% if @user.badges.count > 0 %>
    <% @user.badges.each do |badge| %>
      <img style="max-width: 230px;" src="<%= badge.badge_image_url %>">
    <% end %>
  <% end %>
  <h3><u>Mentorship Details</u></h3>
  <%= form_for ([:internal, @user]) do |f| %>
    <% if @user.banned_from_mentorship %>
      <p style="background-color:red; color:white;"> USER IS BANNED FROM MENTORSHIP, SEE NOTES BELOW </p>
    <% else %>
      <p>Ban user from participating in mentorship program <%= f.check_box :ban_from_mentorship %></p>
    <% end %>
    <%= f.label :offering_mentorship %>
    <%= f.check_box :offering_mentorship %>
    <br>
    <% if !@user.mentor_description.blank? %>
      <p>"<%= @user.mentor_description %>"</p>
    <% end %>
    <%= f.label :seeking_mentorship %>
    <%= f.check_box :seeking_mentorship %>
    <br>
    <% if !@user.mentee_description.blank? %>
      <p>"<%= @user.mentee_description %>"</p>
    <% end %>
    <h3><u>Mentorship Matches</u> </h3>
    <% if @user.mentors.count > 0 %>
      <h4> Mentor(s):</h4>
      <ul>
      <% @user_mentor_relationships.each do |relationship| %>
        <li>
          <a href="https://dev.to/<%= User.find(relationship.mentor_id).username %>" target=">blank">@<%= User.find(relationship.mentor_id).username %></a>
          <% if relationship.active %>
            <span style="color:green"><em> (active)</em></span>
          <% else %>
            <span style="color:red"><em> (inactive)</em></span>
          <% end %>
        </li>
      <% end %>
      </ul>
    <% else %>
      <em>This member does not have any mentorship relationships right now.</em>
      <br />
    <% end %>
    <br>
    <%= f.label :add_mentor %>
    <%= f.text_field :add_mentor, placeholder:"user id#" %>
    <% if @user.mentees.count > 0 %>
      <h4>Mentee(s):</h4>
      <ul>
      <% @user_mentee_relationships.each do |relationship| %>
        <li><a href="https://dev.to/<%= User.find(relationship.mentee_id).username %>" target=">blank">@<%= User.find(relationship.mentee_id).username %></a>
        <% if relationship.active %>
          <span style="color:green"><em> (active)</em></span>
        <% else %>
          <span style="color:red"><em> (inactive)</em></span>
        <% end %>
        </li>
      <% end %>
      </ul>
    <% end %>
    <br>
    <%= f.label :add_mentee %>
    <%= f.text_field :add_mentee, placeholder:"user id#" %>
    <h3><u>Mentorship Notes</u></h3>
    <% if @user.notes.count > 0 %>
      <% @user.notes.each do |note| %>
        <p><em><%= note.created_at.strftime("%d %B %Y %H:%M UTC") %> by <%= User.find(note.author_id).username %></em> - <%= note.content %></p>
      <% end %>
      <br>
      <h4>Add new mentorship note</h4>
      <%= f.text_area :mentorship_note %>
    <% else %>
      <%= f.text_area :mentorship_note %>
    <% end %>
    <br/>
    <%= f.submit %>
  <% end %>
</div>

<% if @user.seeking_mentorship %>
  <h2> Mentee Description </h2>
        <p style="position:sticky;top:50px;background:white;z-index:1000;padding:15px;border:2px solid black"><%= @user.mentee_description %></p>

  <h2> Possible Mentors </h2>
  <% count = 0 %>
  <% MentorRelationship.
      unmatched_mentors.where.not(mentor_form_updated_at: nil, id: @user.id).
      order("mentor_form_updated_at DESC").limit(175).
      sort_by { |possible_mentor| UserSimilarity.new(@user, possible_mentor).score }.reverse.
      first(20).each do |possible_mentor| %>
    <div class="row" style="font-size:0.9em">
      <div class="col-md-2">
        <img src="<%= possible_mentor.profile_image_90 %>" style="border-radius:100px;width:50px;height:50px;" />
        <br/>
        <a href="/<%= possible_mentor.username %>" target="_blank">@<%= possible_mentor.username %></a>
        <br/>
        <a href="/internal/users/<%= possible_mentor.id %>" target="_blank">Internal(<%= possible_mentor.id %>)</a>
      </div>
      <div class="col-md-3" style="border-left:1px solid black">
        <h4>Tag Intersection</h4>
        <%= UserSimilarity.new(@user, possible_mentor).tag_intersection.join(", ") %>
      </div>
      <div class="col-md-3">
        <h4>Mentor description</h4>
        <%= possible_mentor.mentor_description %>
      </div>
      <div class="col-md-3">
        <h4>Skills/Languages</h4>
        <%= possible_mentor.mostly_work_with %>
      </div>
      <div class="col-md-1">
        <h4>Action</h4>
        <%= form_for ([:internal, @user]) do |f| %>
          <%= f.hidden_field :quick_match, value: true %>
          <%= f.hidden_field :add_mentor, value: possible_mentor.id %>
          <%= f.submit "Match!" %>
        <% end %>
      </div>
    </div>
  <% end %>
<% end %>

<h2> Recent Emails </h2>
<% @user.email_messages.order("sent_at DESC").limit(50).each do |email| %>
  <div class="row">
    <a href="/admin/email_messages/<%= email.id %>"><%= email.subject %></a> <%= email.sent_at&.strftime("%b %e '%y") %>
  </div>
<% end %>